species: Kinamaze

seq_info:
  type: WGS
  stranded: yes
  mode: PE
  replicate: 4

path: /var/data/16.Richa_16s/

samples:
  - L1
  - L2
  
cpu: 30

cov_num: 18000

Rscript_path: /home/galaxy/R/3.5.0/bin/Rscript

ref_gold_seq: /home/galaxy/Gmatic5/genome/16s/gold.fa

pick_otu_params: /home/galaxy/Gmatic5/genome/16s/param.txt

alpha_params: /home/galaxy/Gmatic5/genome/16s/alpha_params.txt

adapter: /home/galaxy/software/miniconda3/pkgs/trimmomatic-0.36-4/share/trimmomatic-0.36-4/adapters/TruSeq2-PE.fa

index: /home/galaxy/Gmatic5/genome/tair10/tair10 

genome: /home/galaxy/Gmatic5/genome/tair10/tair.fa
